version: '3.7'
 
services:
  api:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: >
        bash -c 'cd app &&
        sbt run'
    volumes:
      - ./backend:/server
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d